### ISSUE TITLE
Write a product planning: Definition of Done

### ISSUE THREAD

**Issue by eriksennema** [MatthijsKok/TI2806-Contextproject#35]
Definition of Done (backlog items, sprints, releases)

**Comment by RvdK** [comment]
I disagree with a definition of done for the sprint since it is a specific timeslot if you do not finish al tasks within this timeslot the sprint will still be done you simply have to keep the user stories open and place them in the next sprint (or even later if the priority is low) 

I would use a definition of done for a user story instead of feature

**Comment by Ishadijcks** [comment]
How would you define the definition of done for a sprint, or just not include it since it's a timeslot and can't really be 'done'? Or should it say something like 'a sprint is a timeslot so it can't be done, but we consider the work of a sprint done when...' en dan wat er nu staat?

**Comment by RvdK** [comment]
Ik zou gewoon helemaal geen definition of done definiëren voor een sprint je zou nog iets kunnen zeggen over dat een succesvolle sprint eentje is waarbij alle geplande userstories af zijn.

**Comment by Ishadijcks** [comment]
Ik heb nu dit: "Since a sprint is a specific time period, the sprint is done at the end of the week. If not all user stories from the sprint are implemented, they will have to be carried over to the next sprint. The work of a sprint is done when the application contains all features that were planned for that sprint. We have to run all the tests that we did for testing the features, with the addition of user tests to confirm the product works properly. We will also confirm with the client that we build the features in our sprint the way he wanted."

**Comment by RvdK** [comment]
Ik vind het prima zo enig detail is natuurlijk wel dat niet elke user story ook features voor de app hoeft te bevatten (zoals deze us) maar denk niet dat dat heel belangrijk is
