### ISSUE TITLE
Create banking interface

### ISSUE THREAD

**Issue by RvdK** [MatthijsKok/TI2806-Contextproject#42]
build a generalized banking interface with which the challenge/response system can interact 

This interface should enable us to easily add new banks without changing the rest of the code

it should allow you to:
- connect to a bank account
- send money to another account with a customizable comment
- get all incoming transaction from the connected account preferably over a specific time slot

#51 Design task
#52 Build interface

**Comment by joskuijpers** [comment]
Async stuff: http://randomdotnext.com/retrofit-rxjava/

**Comment by joskuijpers** [comment]
For this, I needed to figure out what is possible with Android/Java. Especially regarding async and network handling. So I spent about 8 hours today to prototype stuff with Retrofit, Gson and custom code. It is not done yet. It is now practically possible to automatically verify and add signatures, however, I need to re-add Gson to that because it cant do: Raw -> Verify -> Parse Gson. Instead, I will need to do: Raw -> Verify and Parse Gson. So re-implement that part a bit.

Should not be too hard... 

To test out the whole communication, especially with sessions and stuff, I already wrote a keypair generator, and a sign and verify function. This is currently separate from the cryptography stuff from the challenge.
